version: "3.7"
services:
  coldfusion:
    image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
    container_name: coldfusion
    hostname: coldfusion
    networks:
      - coldfusion
    ports:
      - "80:8500"
    volumes:
      - "./www:/app"
    environment:
      acceptEULA: "YES"
      password: "C0ldFusi0n"
      enableSecureProfile: "false"
    healthcheck:
      test: curl -f http://localhost/
      interval: 1m
      timeout: 3s    
networks:
  coldfusion: