version: '3.3'

networks:
  drupal:

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drupal  
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html      
    restart: always
    networks:
        - drupal

  dbdrupal:
    image: mysql:latest
    container_name: dbdrupal
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db-data:/var/lib/mysql  
    networks:
      - drupal

